package com.example.chermn.model;

import java.util.Objects;

/**
 * Represents a base user in the application.
 * <p>
 * This class provides shared fields and validation logic for all user types,
 * including Students, Parents, and Teachers. Subclasses extend this class to
 * inherit common user attributes such as name, username, password, and school.
 */
public class Users {

    /** The unique ID of the user (auto-incremented in the database). */
    private int id;

    /** The username or email used for login. */
    private String userName;

    /** The user's first name. */
    private String firstName;

    /** The user's last name. */
    private String lastName;

    /** The user's password. */
    private String password;

    /** The name of the user's school. */
    private String schoolName;

    /**
     * Creates a new user with a specified ID.
     *
     * @param id the unique user ID
     * @param userName the username or email
     * @param firstName the user's first name
     * @param lastName the user's last name
     * @param password the user's password
     * @param schoolName the name of the user's school
     */
    public Users(int id, String userName, String firstName, String lastName,
                 String password, String schoolName) {
        this.id = id;
        setUsername(userName);
        setFirstName(firstName);
        setLastName(lastName);
        setPassword(password);
        setSchoolName(schoolName);
    }

    /**
     * Creates a new user without specifying an ID.
     * Used when the ID is auto-generated by the database.
     *
     * @param userName the username or email
     * @param firstName the user's first name
     * @param lastName the user's last name
     * @param password the user's password
     * @param schoolName the name of the user's school
     */
    public Users(String userName, String firstName, String lastName,
                 String password, String schoolName) {
        setUsername(userName);
        setFirstName(firstName);
        setLastName(lastName);
        setPassword(password);
        setSchoolName(schoolName);
    }

    /**
     * Returns the user's ID.
     *
     * @return the user ID
     */
    public int getid() {
        return id;
    }

    /**
     * Returns the user's username or email.
     *
     * @return the username
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Returns the user's first name.
     *
     * @return the first name
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Returns the user's last name.
     *
     * @return the last name
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Returns the user's password.
     *
     * @return the password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Returns the user's school name.
     *
     * @return the school name
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * Sets the user's first name after validating and formatting it.
     *
     * @param firstName the first name to set
     */
    public void setFirstName(String firstName) {
        validateName(firstName, "First name");
        this.firstName = formatName(firstName);
    }

    /**
     * Sets the user's last name after validating and formatting it.
     *
     * @param lastName the last name to set
     */
    public void setLastName(String lastName) {
        validateName(lastName, "Last name");
        this.lastName = formatName(lastName);
    }

    /**
     * Sets the user's password.
     * Must be at least 5 characters long.
     *
     * @param password the password to set
     * @throws IllegalArgumentException if the password is too short
     */
    public void setPassword(String password) {
        if (password == null || password.length() < 5) {
            throw new IllegalArgumentException("Password must be a minimum of 5 chars");
        }
        this.password = password;
    }

    /**
     * Sets the user's school name after validating and formatting it.
     *
     * @param schoolName the school name to set
     */
    public void setSchoolName(String schoolName) {
        validateName(schoolName, "School name");
        this.schoolName = formatSchoolName(schoolName);
    }

    /**
     * Sets the user's ID.
     *
     * @param autoIncrementedId the ID assigned by the database
     */
    public void setId(int autoIncrementedId) {
        this.id = autoIncrementedId;
    }

    /**
     * Sets the user's username.
     *
     * @param username the username to set
     * @throws IllegalArgumentException if the username is blank
     */
    public void setUsername(String username) {
        if (username == null || username.isBlank()) {
            throw new IllegalArgumentException("Username must not be left blank");
        }
        this.userName = username;
    }

    /**
     * Returns a string representation of the user.
     *
     * @return a formatted string containing user details
     */
    @Override
    public String toString() {
        return "User Information{" +
                "id=" + id +
                ", username='" + userName + '\'' +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                '}';
    }

    /**
     * Formats a name by trimming whitespace, converting to lowercase,
     * and capitalizing the first letter.
     *
     * @param name the name to format
     * @return the formatted name
     */
    private String formatName(String name) {
        name = name.trim().toLowerCase();
        return Character.toUpperCase(name.charAt(0)) + name.substring(1);
    }

    /**
     * Validates a name field using regex rules.
     *
     * @param name the value to validate
     * @param fieldName the label used in error messages
     * @throws IllegalArgumentException if validation fails
     */
    private void validateName(String name, String fieldName) {
        if (name == null || name.trim().isEmpty()) {
            throw new IllegalArgumentException(fieldName + " must not be empty.");
        }

        if (Objects.equals(fieldName, "School name")) {
            if (!name.matches("^[a-zA-Z ]+$")) {
                throw new IllegalArgumentException(fieldName + " must contain only letters or spaces.");
            }
        } else {
            if (!name.matches("^[a-zA-Z]+$")) {
                throw new IllegalArgumentException(fieldName + " must contain only letters.");
            }
        }
    }

    /**
     * Formats a school name by capitalizing each word.
     *
     * @param schoolName the school name to format
     * @return the formatted school name
     */
    private String formatSchoolName(String schoolName) {
        String[] splitStringArray = schoolName.split(" ");
        String formattedString = "";

        for (String splitString : splitStringArray) {
            formattedString += formatName(splitString) + " ";
        }

        return formattedString.trim();
    }
}