package com.example.chermn.controller;

import java.io.IOException;

import com.example.chermn.OnBoarding;
import com.example.chermn.Session;
import com.example.chermn.dao.UserDAO;
import com.example.chermn.model.Student;
import com.example.chermn.model.Users;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

/**
 * Controller for the base profiles screens.
 * Handles the base profile functionalities, such as displaying screens, changing passwords,
 * and signing out.
 */
public abstract class BaseProfileController {

    /**
     * Abstract method that gets the type of StackPane used
     * @return the container type
     */
    protected abstract StackPane getContainer();

    // instantiate userDAO to access
    /**
     * Instantiates the database to allow access.
     */
    protected UserDAO userDAO = new UserDAO();

    // defining variable for current logged-in user
    /**
     * Defines the variable for the current, logged-in user.
     */
    protected Users user;


    /**
     * Initialises the controller before the screen is displayed.
     * Sets the user as the current logged-in user stored in Session.
     */
    public void initialize() {
        user = Session.getCurrentUser();
    }

    /**
     * Loads the different screens corresponding to the type of user.
     * @param fxml the string format of the fxml file for the profile screen.
     */
    public void loadView(String fxml) {
        try {
            FXMLLoader loader = new FXMLLoader(
                BaseProfileController.class.getResource("/com/example/chermn/" + fxml)
            );
            
            Parent view = loader.load();
                        
            getContainer().getChildren().setAll(view);
        
        } catch (IOException e) {
            e.printStackTrace();
        }

}

    /**
     * Sets the profile type depending on the inputted user's type.
     * @param user the current logged-in user
     * @return the fxml file's name depending on the type of user.
     */
    private String setProfileType(Users user) {
        String fxml;
        if (userDAO.getUserByUsername(user.getUserName()) instanceof Student student)
        {
            fxml = "change-password.fxml";
        }
        else
        {
            fxml = "teacher-changePassword.fxml";
        }

        return fxml;
    }

    /**
     * Handles the change password button click.
     * Loads the specific profile screen depending on the current user's type.
     * @param event the action event generated by clicking the change password button.
     */
    @FXML
    protected void changePasswordButtonClick(ActionEvent event) {
        loadView(setProfileType(user));
    }

    /**
     * Handles the sign-out button click.
     * Loads the onboarding screen to allow the user to sign back in, or create new account.
     * @param event the action event generated by clicking the sign-out button.
     * @throws IOException if the sign-out event is not allowed.
     */
    @FXML
    protected void signOutButtonClick(ActionEvent event) throws IOException {
        Stage stage = (Stage) ((Node) event.getSource())
                .getScene().getWindow();
        FXMLLoader fxmlLoader = new FXMLLoader(OnBoarding.class.getResource("onboarding-screen.fxml"));
        Scene scene = new Scene(fxmlLoader.load(), OnBoarding.WIDTH, OnBoarding.HEIGHT);
        stage.setScene(scene);
    }

}
