package com.example.chermn.controller;

// the profile will display the users information and allows them to update

import com.example.chermn.OnBoarding;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;
import javafx.event.ActionEvent;
import java.io.IOException;

/**
 * Controller for the profile screen.
 * Handles functionality between different profile screens, such as
 * displaying screens, signing out, and closing screen.
 * Extends the {@code BaseProfileController} to reuse shared profile functionality.
 */
public class ProfileController extends BaseProfileController{

    @FXML
    private StackPane contentPane;
    @FXML
    private Button changePasswordButton;
    @FXML
    private Button levelProgressButton;
    @FXML
    private Button userProfileButton;
    @FXML
    private Button closeButton;
    @FXML
    private Button signOutButton;

    /**
     * Gets the type of StackPane used within the profile.
     * @return the type of StackPane.
     */
    @Override
    protected StackPane getContainer() {
        return contentPane;
    }

    /**
     * Handles the user profile button click event.
     * Loads the update user details view.
     */
    @FXML
    private void userProfileButtonClick() {
        loadView("update-user-details.fxml");
    }

    /**
     * Handles the level progress button click event.
     * Loads the level progress view.
     */
    @FXML
    private void levelProgressButtonClick() {
        loadView( "view-level-progress.fxml");

    }

    /**
     * Handles the change password button click event.
     * Calls the super method from the extended class, {@code BaseProfileController}
     * @param event the action event generated by clicking the change password button.
     */
    @FXML
    @Override
    protected void changePasswordButtonClick(ActionEvent event) {
        super.changePasswordButtonClick(event);
    }

    /**
     * Handles the close button click event.
     * Closes the profile view, and redirects the user back to the homepage.
     * @throws IOException if can't load the homepage screen.
     */
    @FXML
    protected void closeButtonClick() throws IOException {
        Stage stage = (Stage) closeButton.getScene().getWindow();
        FXMLLoader loader = new FXMLLoader(OnBoarding.class.getResource("homepage.fxml"));
        Scene scene = new Scene(loader.load(), OnBoarding.WIDTH, OnBoarding.HEIGHT);
        stage.setScene(scene);
    }

    /**
     * Handles the sign-out button click event.
     * Calls the super method from the extended class, {@code BaseProfileController}
     * @param event the action event generated by clicking the sign-out button.
     * @throws IOException if the onboarding screen can't be loaded.
     */
    @Override
    protected void signOutButtonClick(ActionEvent event) throws IOException {
        super.signOutButtonClick(event);
    }


    /**
     * Public constructor of profile controller class.
     */
    public ProfileController() {
    }

}