package com.example.chermn.controller;

import com.example.chermn.OnBoarding;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;
import javafx.event.ActionEvent;
import java.io.IOException;

/**
 * Controller for the profile screen.
 * <p>
 * Handles navigation between profile-related views, including updating user details,
 * viewing level progress, changing passwords, signing out, and closing the profile screen.
 * Extends {@code BaseProfileController} to reuse shared profile functionality.
 */
public class ProfileController extends BaseProfileController {

    @FXML
    private StackPane contentPane;
    @FXML
    private Button changePasswordButton;
    @FXML
    private Button levelProgressButton;
    @FXML
    private Button userProfileButton;
    @FXML
    private Button closeButton;
    @FXML
    private Button signOutButton;

    /**
     * Default constructor for ProfileController.
     * Required for JavaFX controller instantiation.
     */
    public ProfileController() {}

    /**
     * Returns the container StackPane used to load profile subviews.
     *
     * @return the StackPane that holds dynamically loaded profile views
     */
    @Override
    protected StackPane getContainer() {
        return contentPane;
    }

    /**
     * Handles the user profile button click event.
     * Loads the update-user-details view into the profile container.
     */
    @FXML
    private void userProfileButtonClick() {
        loadView("update-user-details.fxml");
    }

    /**
     * Handles the level progress button click event.
     * Loads the level progress view into the profile container.
     */
    @FXML
    private void levelProgressButtonClick() {
        loadView("view-level-progress.fxml");
    }

    /**
     * Handles the change password button click event.
     * Delegates to the superclass implementation in {@code BaseProfileController}.
     *
     * @param event the action event generated by clicking the change password button
     */
    @FXML
    @Override
    protected void changePasswordButtonClick(ActionEvent event) {
        super.changePasswordButtonClick(event);
    }

    /**
     * Handles the close button click event.
     * Closes the profile view and returns the user to the homepage.
     *
     * @throws IOException if the homepage FXML cannot be loaded
     */
    @FXML
    protected void closeButtonClick() throws IOException {
        Stage stage = (Stage) closeButton.getScene().getWindow();
        FXMLLoader loader = new FXMLLoader(OnBoarding.class.getResource("homepage.fxml"));
        Scene scene = new Scene(loader.load(), OnBoarding.WIDTH, OnBoarding.HEIGHT);
        stage.setScene(scene);
    }

    /**
     * Handles the sign-out button click event.
     * Delegates to the superclass implementation in {@code BaseProfileController}.
     *
     * @param event the action event generated by clicking the sign-out button
     * @throws IOException if the onboarding screen cannot be loaded
     */
    @Override
    protected void signOutButtonClick(ActionEvent event) throws IOException {
        super.signOutButtonClick(event);
    }
}