package com.example.chermn.controller;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.image.ImageView;
import javafx.scene.layout.StackPane;
import java.io.IOException;

/**
 * Controller for the parent and teacher's homepage screen.
 * Handles navigating between different screen stemming off the homepage.
 */
public class TeacherParentHomescreenController extends BaseProfileController {
    @FXML
    private Button signOutButton;
    @FXML
    private ImageView fullBackground;
    @FXML
    private StackPane contentArea;

    /**
     * Handles the sign-out button click event.
     * Resets the current logged-in user, and redirects to onboarding page.
     * @param event the action event generated by clicking the sign-out button.
     * @throws IOException if the sign-out can't be processed
     */
    @Override
    @FXML
    protected void signOutButtonClick(ActionEvent event) throws IOException {
        super.signOutButtonClick(event);
    }

    /**
     * Handles the main dashboard actions.
     * Resets the content area to display the main, clear background.
     * @param actionEvent the action event generated by clicking the show dashboard button
     */
    @FXML
    private void showDashboard(ActionEvent actionEvent) {
        // want to change opacity of background picture back to normal
        fullBackground.setOpacity(1);

        // remove any loaded sub-view to get the basic dashboard back again
        contentArea.getChildren().clear();
    }


    /**
     * Gets the content area that will display the information.
     * @return the content area type
     */
    @Override
    protected StackPane getContainer() {
        // returns the stack pane for the teacher user
        return contentArea;
    }

    /**
     * Handles the show students details click event.
     * Changes the background picture opacity, and loads the student details screen.
     * @param actionEvent the action event generated by the show student's details button
     */
    @FXML
    private void showStudentsDetails(ActionEvent actionEvent) {
        // want to change opacity of background picture so that details displayed on top
        fullBackground.setOpacity(0.4);

        // assigning the container for load view
        // change to the view students details screen
        loadView( "student-details-page.fxml");

    }

    /**
     * Handles the show user details click event.
     * Changes the background picture's opacity, and loads the user details screen.
     * @param actionEvent the action event generated by the show user details button.
     */
    @FXML
    private void showUserDetails(ActionEvent actionEvent) {
        // changing opacity of background picture to display details over top
        fullBackground.setOpacity(0.4);

        // change to the user details screen
        loadView( "teacher-viewDetails.fxml");
    }

    /**
     * Handles the change password click event.
     * Changes the background picture's opacity, and loads the change password screen.
     * @param event the action event generated by the change password button.
     */
    @FXML
    @Override
    protected void changePasswordButtonClick(ActionEvent event) {
        // changing opacity of background picture to display details over top
        fullBackground.setOpacity(0.4);

        super.changePasswordButtonClick(event);
    }


    /**
     * Public constructor of teacher parent homescreen controller class.
     */
    public TeacherParentHomescreenController() {
    }

}

