package com.example.chermn.controller;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.layout.StackPane;
import java.io.IOException;

/**
 *  Controller for the update user details screen.
 *  Handles updating and displaying the current user's profile information.
 *  Extends the {@code ProfileController} to reuse shared profile functionality.
 */
public class UpdateUserDetailsController extends ProfileController {

// the profile will display the students information and allows them to update
    @FXML
    private StackPane contentPane;

    @FXML
    private TextField firstNameField;

    @FXML
    private TextField lastNameField;

    @FXML
    private Label usernameLabel;

    @FXML
    private TextField emailField;

    @FXML
    private TextField schoolField;

    @FXML
    private Button updateButton;


    /**
     * Initialises the controller before the screen is displayed.
     * Loads the current user's details into the text fields.
     */
    @Override
    public void initialize() {
        super.initialize();

        // pulls the current user's stats/levels for the fields
        fillUserDetails();
    }



    /**
     * Fills the UI field texts with the current user's details,
     * such as the first name, last name, username, and school name.
     */
    private void fillUserDetails() {

            firstNameField.setText(user.getFirstName());
            lastNameField.setText(user.getLastName());
            usernameLabel.setText(user.getUserName());
            // there is no email field for students as of yet
            // emailField.setText(currentUser.getEmail());
            schoolField.setText(user.getSchoolName());

        }

    /**
     * Handles the update button click event.
     * Retrieves the updated values from the text fields,
     * updates the current user, and saves changes to the database.
     * Displays an error message if validation of user details fails.
     * @param actionEvent the action event generated by clicking the update button.
     */
    @FXML
        private void updateButtonClick(ActionEvent actionEvent) {
        // tries to collect the user's updated data, updates user and user details
        try {
            // collect the data written in the text fields
            String firstName = firstNameField.getText().trim();
            String lastName = lastNameField.getText().trim();
            String schoolName = schoolField.getText().trim();

            // pass it through to update method
            updateUserDetails(firstName, lastName, schoolName);

            // updates the user in the database
            userDAO.updateUser(user);

            // update the text fields with current data stored in the database
            fillUserDetails();
        }
        // catches any illegal argument exceptions and displays them to the user through show alert method
        catch (IllegalArgumentException exception) {
            showAlert(Alert.AlertType.ERROR,
                    "Invalid Details",
                    exception.getMessage());
        }
    }


    /**
     * Updates the current user's details if the provided values
     * differ from the existing stored values within the database.
     * @param firstName the updated user's first name.
     * @param lastName the updated user's last name.
     * @param schoolName the updated user's school name.
     */
        private void updateUserDetails(String firstName, String lastName, String schoolName) {

            // checks to ensure that the first name has been modified before updating
            if (firstName != null && !firstName.equals(user.getFirstName())) {
                user.setFirstName(firstName);
            }
            // checks to ensure that the last name has been modified before updating
            if (lastName != null && !lastName.equals(user.getLastName())) {
                user.setLastName(lastName);
            }
            // checks to ensure that the school name has been modified before updating
            if(schoolName != null && !schoolName.equals(user.getSchoolName())) {
                user.setSchoolName(schoolName);
            }
        }


    /**
     * Displays an alert message to the user.
     * @param alertType the type of alert to display.
     * @param title the alert title.
     * @param message the alert message.
     */
    private void showAlert(Alert.AlertType alertType, String title, String message) {
        Alert alert = new Alert(alertType);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }



    }

