package com.example.chermn.controller;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import java.io.IOException;

/**
 * Controller for the update teacher details screen.
 * Handles updating and displaying the current teacher's profile information.
 * Extends the {@code TeacherParentHomescreenController} to reuse shared profile functionality.
 */
public class UpdateTeacherDetailsController extends TeacherParentHomescreenController{
    @FXML
    private Label usernameLabel;
    // public TextField emailField;
    @FXML
    private TextField firstNameField;
    @FXML
    private TextField lastNameField;
    @FXML
    private TextField schoolField;

    /**
     * Initialises the controller before the screen is displayed.
     * Loads the current user's details into the text fields.
     */
    @Override
    public void initialize() {
        super.initialize();

        // pulls the current user's stats/levels for the fields
        fillUserDetails();
    }

    /**
     * Handles the change password button click event.
     * Calls the method from the extended class.
     * @param event the action event generated by clicking the change password button.
     */
    @Override
    protected void changePasswordButtonClick(ActionEvent event) {
        super.changePasswordButtonClick(event);
    }

    /**
     * Handles the sign-out button click event.
     * Calls the method from the extended class.
     * @param event the action event generated by clicking the sign-out button.
     * @throws IOException throws exception if sign-out can't be handled.
     */
    @Override
    protected void signOutButtonClick(ActionEvent event) throws IOException {
        super.signOutButtonClick(event);
    }



    // Set the text fields with the current users information when the UI loads

    /**
     * Fills the UI field texts with the current user's details,
     * such as the first name, last name, username, and school name.
     */
    private void fillUserDetails() {

        firstNameField.setText(user.getFirstName());
        lastNameField.setText(user.getLastName());
        usernameLabel.setText(user.getUserName());
        // there is no email field for students as of yet
        // emailField.setText(currentUser.getEmail());
        schoolField.setText(user.getSchoolName());

    }

    /**
     * Handles the update button click event.
     * Retrieves the updated values from the text fields,
     * updates the current user, and saves changes to the database.
     * Displays an error message if validation of user details fails.
     * @param actionEvent the action event generated by clicking the update button.
     */
    @FXML
    private void updateButtonClick(ActionEvent actionEvent) {

        // collect the data written in the text fields
        String firstName = firstNameField.getText().trim();
        String lastName = lastNameField.getText().trim();
        String schoolName = schoolField.getText().trim();


        // pass it through to update method
        updateUserDetails(firstName, lastName, schoolName);

        // updates the user in the database
        userDAO.updateUser(user);

        // update the text fields with current data stored in the database
        fillUserDetails();

    }

    /**
     * Updates the current user's details if the provided values
     * differ from the existing stored values within the database.
     * @param firstName the updated user's first name.
     * @param lastName the updated user's last name.
     * @param schoolName the updated user's school name.
     */
    private void updateUserDetails(String firstName, String lastName, String schoolName) {

        if (firstName != null && !firstName.equals(user.getFirstName())) {
            user.setFirstName(firstName);
        }

        if (lastName != null && !lastName.equals(user.getLastName())) {
            user.setLastName(lastName);
        }

        if(schoolName != null && !schoolName.equals(user.getSchoolName())) {
            user.setSchoolName(schoolName);
        }
    }

    /**
     * Public constructor of update teacher details controller class.
     */
    public UpdateTeacherDetailsController() {
    }
}
